In [260]:
#importing basis 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [261]:
#get the train and test dataset
train_df=pd.read_excel('Data_Train.xlsx')
test_df=pd.read_excel('Test_set.xlsx')

In [262]:
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [263]:
#concat both the train and test datasets ,so that cleaning and eda and fearture extraction can be done together ,instead of doing it twice
df = pd.concat([train_df, test_df], ignore_index=True)
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [264]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [265]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Date_of_Journey  13354 non-null  str
 2   Source           13354 non-null  str
 3   Destination      13354 non-null  str
 4   Route            13353 non-null  str
 5   Dep_Time         13354 non-null  str
 6   Arrival_Time     13354 non-null  str
 7   Duration         13354 non-null  str
 8   Total_Stops      13353 non-null  str
 9   Additional_Info  13354 non-null  str
 10  Price            10683 non-null  float64
dtypes: float64(1), str(10)
memory usage: 1.1 MB

In [266]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [267]:
#eda is done extensively in perviously ,now lets focus on feature engineering
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [268]:
# all the attributes are str ,so
#Date_of_Journey can be divided into day, month, year
df['Date_of_Journey'].str.split('/')

0        [24, 03, 2019]
1         [1, 05, 2019]
2         [9, 06, 2019]
3        [12, 05, 2019]
4        [01, 03, 2019]
              ...
13349     [6, 06, 2019]
13350    [27, 03, 2019]
13351     [6, 03, 2019]
13352     [6, 03, 2019]
13353    [15, 06, 2019]
Name: Date_of_Journey, Length: 13354, dtype: object

In [269]:
df.shape

(13354, 11)

In [270]:
df['Date']=df['Date_of_Journey'].str.split('/').str[0]
df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df['Year']=df['Date_of_Journey'].str.split('/').str[2]

In [271]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

In [272]:
#now as date ,month,year is added ,lets remove Date_of_Journey
df=df.drop('Date_of_Journey',axis=1)
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

In [273]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Arrival_Time     13354 non-null  str
 6   Duration         13354 non-null  str
 7   Total_Stops      13353 non-null  str
 8   Additional_Info  13354 non-null  str
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  object
 11  Month            13354 non-null  object
 12  Year             13354 non-null  object
dtypes: float64(1), object(3), str(9)
memory usage: 1.3+ MB

In [274]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Date', 'Month',
       'Year'],
      dtype='str')

In [275]:
#as we can see date,month,year ka datatype is object , lets us convert to int
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [276]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Arrival_Time     13354 non-null  str
 6   Duration         13354 non-null  str
 7   Total_Stops      13353 non-null  str
 8   Additional_Info  13354 non-null  str
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
dtypes: float64(1), int64(3), str(9)
memory usage: 1.3 MB

In [277]:
#lets now move on to next feature that is arrival_time
df['Arrival_Time'].str.split(' ')

0        [01:10, 22, Mar]
1                 [13:15]
2        [04:25, 10, Jun]
3                 [23:30]
4                 [21:35]
               ...
13349    [20:25, 07, Jun]
13350             [16:55]
13351    [04:25, 07, Mar]
13352             [19:15]
13353             [19:15]
Name: Arrival_Time, Length: 13354, dtype: object

In [278]:
df['Arrival_Time']=df['Arrival_Time'].str.split(' ').str[0]

In [279]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [280]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  str
 7   Total_Stops      13353 non-null  str
 8   Additional_Info  13354 non-null  str
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(1), str(8)
memory usage: 1.3+ MB

In [281]:
#i forgot to check for null values ,which should be done in EDA
df.isnull().sum()
#there in no much null values

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [282]:
#Arrival_Time can be further be divided into hour and min
df['Arrival_Hour']=df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Minute']=df['Arrival_Time'].str.split(':').str[1]
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35

In [283]:
#drop arrival_time
df=df.drop('Arrival_Time',axis=1)

In [284]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Duration         13354 non-null  str
 6   Total_Stops      13353 non-null  str
 7   Additional_Info  13354 non-null  str
 8   Price            10683 non-null  float64
 9   Date             13354 non-null  int64
 10  Month            13354 non-null  int64
 11  Year             13354 non-null  int64
 12  Arrival_Hour     13354 non-null  object
 13  Arrival_Minute   13354 non-null  object
dtypes: float64(1), int64(3), object(2), str(8)
memory usage: 1.4+ MB

In [285]:
#covert the datatype
df['Arrival_Hour']=df['Arrival_Hour'].astype(int)
df['Arrival_Minute']=df['Arrival_Minute'].astype(int)

In [286]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Duration         13354 non-null  str
 6   Total_Stops      13353 non-null  str
 7   Additional_Info  13354 non-null  str
 8   Price            10683 non-null  float64
 9   Date             13354 non-null  int64
 10  Month            13354 non-null  int64
 11  Year             13354 non-null  int64
 12  Arrival_Hour     13354 non-null  int64
 13  Arrival_Minute   13354 non-null  int64
dtypes: float64(1), int64(5), str(8)
memory usage: 1.4 MB

In [287]:
#lets do the same for Dep_Time
df['Dep_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1]
df['Dep_Hour']=df['Dep_Hour'].astype(int)
df['Dep_Min']=df['Dep_Min'].astype(int)
df=df.drop('Dep_Time',axis=1)
df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20

In [288]:
#now lets see for route ,which is unneccesary as we have source , destination and no of stops

In [289]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date', 'Month', 'Year', 'Arrival_Hour',
       'Arrival_Minute', 'Dep_Hour', 'Dep_Min'],
      dtype='str')

In [290]:
#lets see Total_Stops
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [291]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [292]:
#we can replace 2 stops with 2 and so on
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,}).fillna(1)

In [293]:
df['Total_Stops'].unique()

array([0., 2., 1., 3., 4.])

In [294]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50

In [295]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Duration         13354 non-null  str
 5   Total_Stops      13354 non-null  float64
 6   Additional_Info  13354 non-null  str
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_Hour     13354 non-null  int64
 12  Arrival_Minute   13354 non-null  int64
 13  Dep_Hour         13354 non-null  int64
 14  Dep_Min          13354 non-null  int64
dtypes: float64(2), int64(7), str(6)
memory usage: 1.5 MB

In [296]:
#dropping route col
df=df.drop('Route',axis=1)

In [297]:
df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20

In [298]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date', 'Month', 'Year', 'Arrival_Hour',
       'Arrival_Minute', 'Dep_Hour', 'Dep_Min'],
      dtype='str')

In [299]:
#lets move on to duration
#convert duration which is written in hour and min into min only
df['Duration_Hour']=df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [300]:
df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_Hour
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2

In [301]:
df[df['Duration']=='5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_Hour
6474,Air India,Mumbai,Hyderabad,5m,2.0,No info,17327.0,6,3,2019,16,55,16,50,5m
13343,Air India,Mumbai,Hyderabad,5m,2.0,No info,NaN,12,3,2019,16,55,16,50,5m

In [302]:
df.drop(6474,axis=0,inplace=True)
df.drop(13343,axis=0,inplace=True)

In [303]:
df[df['Duration']=='5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_Hour, Arrival_Minute, Dep_Hour, Dep_Min, Duration_Hour]
Index: []

In [304]:
df['Duration_Hour']=df['Duration_Hour'].astype(int)

In [305]:
df.info()

<class 'pandas.DataFrame'>
Index: 13352 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  str
 1   Source           13352 non-null  str
 2   Destination      13352 non-null  str
 3   Duration         13352 non-null  str
 4   Total_Stops      13352 non-null  float64
 5   Additional_Info  13352 non-null  str
 6   Price            10682 non-null  float64
 7   Date             13352 non-null  int64
 8   Month            13352 non-null  int64
 9   Year             13352 non-null  int64
 10  Arrival_Hour     13352 non-null  int64
 11  Arrival_Minute   13352 non-null  int64
 12  Dep_Hour         13352 non-null  int64
 13  Dep_Min          13352 non-null  int64
 14  Duration_Hour    13352 non-null  int64
dtypes: float64(2), int64(8), str(5)
memory usage: 1.6 MB

In [306]:
df['Duration_Min']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [307]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_Hour,Duration_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [308]:
df['Duration_Min'].isnull().sum()

np.int64(1284)

In [309]:
df['Duration_Min']=df['Duration_Min'].fillna(0)

In [310]:
df['Duration_Min'].isnull().sum()

np.int64(0)

In [311]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_Hour,Duration_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [312]:
df['Duration_Min']=df['Duration_Min'].astype(int)

In [313]:
df.info()

<class 'pandas.DataFrame'>
Index: 13352 entries, 0 to 13353
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  str
 1   Source           13352 non-null  str
 2   Destination      13352 non-null  str
 3   Duration         13352 non-null  str
 4   Total_Stops      13352 non-null  float64
 5   Additional_Info  13352 non-null  str
 6   Price            10682 non-null  float64
 7   Date             13352 non-null  int64
 8   Month            13352 non-null  int64
 9   Year             13352 non-null  int64
 10  Arrival_Hour     13352 non-null  int64
 11  Arrival_Minute   13352 non-null  int64
 12  Dep_Hour         13352 non-null  int64
 13  Dep_Min          13352 non-null  int64
 14  Duration_Hour    13352 non-null  int64
 15  Duration_Min     13352 non-null  int64
dtypes: float64(2), int64(9), str(5)
memory usage: 1.7 MB

In [314]:
df['Duration_In_Min']=df['Duration_Hour']*60+df['Duration_Min']

In [315]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_Hour,Duration_Min,Duration_In_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50,170
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25,445
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,0,1140
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25,325
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45,285

In [316]:
df=df.drop(['Duration', 'Duration_Min', 'Duration_Hour'], axis=1)

In [317]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_In_Min
0,IndiGo,Banglore,New Delhi,0.0,No info,3897.0,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,2.0,No info,7662.0,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,2.0,No info,13882.0,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,1.0,No info,6218.0,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,1.0,No info,13302.0,1,3,2019,21,35,16,50,285

In [318]:
#lets move to airline
df['Airline'].unique()

<StringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [319]:
# #lets do label encoding for them 
# from sklearn.preprocessing import LabelEncoder
# labelencoder=LabelEncoder()

In [320]:
# df['Airline']=labelencoder.fit_transform(df['Airline'])
# df['Source']=labelencoder.fit_transform(df['Source'])
# df['Destination']=labelencoder.fit_transform(df['Destination'])
# df['Additional_Info']=labelencoder.fit_transform(df['Additional_Info'])
# #here label encoding is done ,u can also do one hot encoding

In [321]:
df = pd.get_dummies(df,columns=['Airline','Source','Destination','Additional_Info'],drop_first=True)

In [322]:
df.head()

,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_In_Min,...,Destination_New Delhi,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897.0,24,3,2019,1,10,22,20,170,...,True,False,False,False,False,False,False,False,True,False
1,2.0,7662.0,1,5,2019,13,15,5,50,445,...,False,False,False,False,False,False,False,False,True,False
2,2.0,13882.0,9,6,2019,4,25,9,25,1140,...,False,False,False,False,False,False,False,False,True,False
3,1.0,6218.0,12,5,2019,23,30,18,5,325,...,False,False,False,False,False,False,False,False,True,False
4,1.0,13302.0,1,3,2019,21,35,16,50,285,...,True,False,False,False,False,False,False,False,True,False

In [324]:
#separating the dataset iinto train and test
train_df = df[df['Price'].notna()]
test_df = df[df['Price'].isna()]

In [325]:
X = train_df.drop('Price', axis=1)
y = train_df['Price']
X = X.astype(int)

In [327]:
X.head()

,Total_Stops,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_In_Min,Airline_Air India,...,Destination_New Delhi,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0,24,3,2019,1,10,22,20,170,0,...,1,0,0,0,0,0,0,0,1,0
1,2,1,5,2019,13,15,5,50,445,1,...,0,0,0,0,0,0,0,0,1,0
2,2,9,6,2019,4,25,9,25,1140,0,...,0,0,0,0,0,0,0,0,1,0
3,1,12,5,2019,23,30,18,5,325,0,...,0,0,0,0,0,0,0,0,1,0
4,1,1,3,2019,21,35,16,50,285,0,...,1,0,0,0,0,0,0,0,1,0

In [328]:
X_test_final = test_df.drop('Price', axis=1)
X_test_final = X_test_final.astype(int)

In [329]:
X_test_final.head()

,Total_Stops,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Min,Duration_In_Min,Airline_Air India,...,Destination_New Delhi,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
10683,1,6,6,2019,4,25,17,30,655,0,...,0,0,0,0,0,0,0,0,1,0
10684,1,12,5,2019,10,20,6,20,240,0,...,0,0,0,0,0,0,0,0,1,0
10685,1,21,5,2019,19,0,19,15,1425,0,...,0,0,0,0,0,1,0,0,0,0
10686,1,21,5,2019,21,0,8,0,780,0,...,0,0,0,0,0,0,0,0,1,0
10687,0,24,6,2019,2,45,23,55,170,0,...,0,0,0,0,0,0,0,0,1,0

In [330]:
print(X_test_final.shape)
print(X.columns.shape)

(2670, 38)
(38,)

In [331]:
#models
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [332]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor()
dt.fit(X, y)

DecisionTreeRegressor()

In [333]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)
rf.fit(X, y)

RandomForestRegressor(random_state=42)

In [335]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [336]:
# Linear Regression
lr.fit(X_train, y_train)

# Decision Tree
dt.fit(X_train, y_train)

# Random Forest
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [337]:
y_pred_lr = lr.predict(X_val)
y_pred_dt = dt.predict(X_val)
y_pred_rf = rf.predict(X_val)

In [338]:
from sklearn.metrics import mean_absolute_error

print("Linear Regression MAE:", mean_absolute_error(y_val, y_pred_lr))
print("Decision Tree MAE:", mean_absolute_error(y_val, y_pred_dt))
print("Random Forest MAE:", mean_absolute_error(y_val, y_pred_rf))

Linear Regression MAE: 1749.5971030371113
Decision Tree MAE: 648.2131492746842
Random Forest MAE: 606.5582976951816

In [339]:
#tuning the random forest
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=25,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_val)

from sklearn.metrics import mean_absolute_error
print("Tuned RF MAE:", mean_absolute_error(y_val, y_pred_rf))

Tuned RF MAE: 645.4994308075396

In [340]:
import numpy as np

y_train_log = np.log1p(y_train)
y_val_log = np.log1p(y_val)

rf.fit(X_train, y_train_log)

y_pred_log = rf.predict(X_val)
y_pred = np.expm1(y_pred_log)

print("MAE after log:", mean_absolute_error(y_val, y_pred))

MAE after log: 626.1493236756384